### ISSUE TITLE
Geoserver stylesheets dont always work

### ISSUE THREAD

**Issue by Scott07uk** [OrdnanceSurvey/OS-OpenMap-Local-stylesheets#5]
When using the Geoserver stylesheets (SLD), there is a problem with either the stylesheet or the data with regard to the SU national grid square.  On lines 308 to 3111 of OML_Roads_backdrop.sld there is a filter checking if "featureCod" equals 15749 (this condition is repeated 2 more times in other sections).  When you load the SU tile data (as a shapefile) for roads into geoserver with this stylesheet the roads will not render because the attribute "featureCod" is missing from some of the features.  I would have expected this to work (as clearly "the lack of featureCod makes it implicity not equal to 15749"), however in Geoserver (and geotools which I believe Geoserver uses), this causes a fatal error in rendering.

**Comment by ghost** [comment]
Thanks for the feedback Scott. This should read "FEATCODE" not "featureCod".
I will get this updated this week but in the mean time I suggest opening the SLD in a text editor and performing a 'replace all' as outlined above.

**Comment by Scott07uk** [comment]
Hi,

Thanks for that, it has certainly fixed that issue, however they road layers still dont always render quite right (though mostly they are good).  Take a look at the screenshot below:
![map_render](https://cloud.githubusercontent.com/assets/18646387/14799323/d444b150-0b33-11e6-90ad-99ef198c621b.png)

This is part of the Basingstoke (Hampshire) ring road, you will see in the middle of the map there is a missing roundabout which connects two ends of Ringway South and two ends of Hackwood Road (the right hand end of Ringway South is actually missing too).  You can see the roads here:

http://www.openstreetmap.org/#map=16/51.2575/-1.0811
and
https://www.google.co.uk/maps/@51.2574936,-1.081625,966m/data=!3m1!1e3

**Comment by ghost** [comment]
Many thanks, we are aware of this issue and are working on it.

**Comment by egil1978** [comment]
Hi Scott, thanks for your comments and apologies for this. Hopefully this issue has now been fixed and the new SLD's are now available for you to download.
Paul.

**Comment by sequel63** [comment]
Thanks for the new SLDs. For me they are better, but still not quite right. Anyone else have the same missing road style and roundabout issues?
![screen shot 2016-05-03 at 11 10 50](https://cloud.githubusercontent.com/assets/9572642/14980387/0eb12a02-1120-11e6-9b85-84d6575edf82.png)

**Comment by egil1978** [comment]
Thanks for the comments. Ill take another look now.
Apologies for the inconvenience

**Comment by egil1978** [comment]
Hi sequel63,
I have fixed the roads SLD so the roads should all now be displaying. I have also added a roundabout case SLD which should sit beneath your road layer.

**Comment by sequel63** [comment]
Thanks, but looks like the problem is still there. The Roads SLD appears to miss a style for Featurecode 15729?

**Comment by egil1978** [comment]
Weird one as that is the error I thought I had fixed!! Try it again it should work this time.

**Comment by sequel63** [comment]
Yes! Looks like you added 15792 ;-).
Thank you!

**Comment by egil1978** [comment]
No probs. Glad we got there in the end
